package io.github.stefanbratanov.jvm.openai;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.List;

/**
 * Represents a streamed chunk of a chat completion response returned by model, based on the
 * provided input.
 */
public record ChatCompletionChunk(
    String id,
    List<Choice> choices,
    long created,
    String model,
    @JsonProperty("system_fingerprint") String systemFingerprint) {

  public record Choice(
      Delta delta,
      int index,
      Logprobs logprobs,
      @JsonProperty("finish_reason") String finishReason) {

    /** A chat completion delta generated by streamed model responses. */
    public record Delta(String role, String content, List<ToolCall> toolCalls) {}
  }
}
