package io.github.stefanbratanov.jvm.openai;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.List;

/** Represents a chat completion response returned by model, based on the provided input. */
public record ChatCompletion(
    String id,
    long created,
    String model,
    @JsonProperty("system_fingerprint") String systemFingerprint,
    List<Choice> choices,
    Usage usage) {

  public record Choice(
      int index,
      Message message,
      Logprobs logprobs,
      @JsonProperty("finish_reason") String finishReason) {

    /** A chat completion message generated by the model. */
    public record Message(String content, List<ToolCall> toolCalls, String role) {}
  }
}
